### ISSUE TITLE
v2.2.0 depends on `OC` global

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-logger#361]
https://github.com/nextcloud/nextcloud-logger/blob/69157312bb071d3152c54f4686aacb2df014042e/lib/LoggerBuilder.ts#L18 doesn't work if `OC` is undefined. That happens with rare loading order problems but also in testing environments.

The library can work without the global, so I wouldn't make this a hard dependency. @susnux how about ``OC?.config?.loglevel`` instead of ``OC.config?.loglevel``?

**Comment by susnux** [comment]
I think that change is fine but then the `OC.debug` is also not defined and must be guarded by using the `?.` operator.

Are the loading problems related to the core? I guess at some point it might get handy to use this library even in the core, as currently it floods the debug console even if nextcloud is configured for production (besides it is not useful logging even if the console is not opened is a heavy operation and measurable decreases the performance).
