### ISSUE TITLE
Administrator Logging Screen goes blank

### ISSUE THREAD

**Issue by mhepplewhite** [nextcloud/nextcloud-logger#364]
After upgrade to NC 24.0.2 logged on as Administrator, Settings -> Logging, content appears then goes blank.

On Ubuntu latest on RPi4 4GB

Fully repeatable on Firefox, Edge, no change after restarts.

Expected behavior
Logging data presented

Desktop (please complete the following information):

    OS: [e.g. iOS] Windows 10
    Browser [e.g. chrome, safari] Firefox, Edge

**Comment by ChristophWurst** [comment]
Report this at https://github.com/nextcloud/server/issues/new/choose.

This is the repo for the logging component *developers* use.
