### ISSUE TITLE
Impossible to import with 2.4.0

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/nextcloud-logger#410]
When importing anything from `@nextcloud/logger` 2.4.0, we get this:

![image](https://user-images.githubusercontent.com/11291457/198274944-190fc652-12b2-4ecf-a688-49a08ae92ac2.png)

Tried with:
* `import { getLoggerBuilder } from '@nextcloud/logger'`
* `import { getLogger } from '@nextcloud/logger'`
* `import { anything } from '@nextcloud/logger'`

Everything works fine after reverting to 2.3.0 with `npm i --save @nextcloud/logger@2.3.0`

**Comment by ChristophWurst** [comment]
Could you link the package and bisect between the two release tags? There were many dependency bumps. I suspect one of them could have broken the export.

**Comment by julien-nc** [comment]
Weirdly enough, it works when linking with the latest commit.
Could it be an issue with the release build process?

**Comment by ChristophWurst** [comment]
I'll try if I can reproduce. Otherwise we can do a 2.4.1 just to have a clear build and see if that resolved the issue.

**Comment by ChristophWurst** [comment]
The package works just fine with Mail. I'm able to use it. Could it be a configuration error of your app? Shall we try with a third?

**Comment by julien-nc** [comment]
You're right. I tried with another app (integration_github) and it works fine. The app with which it does not work is https://github.com/nextcloud/user_oidc .

Webpack config is pretty basic: https://github.com/nextcloud/user_oidc/blob/master/webpack.js
Both apps use the same compilation command, same as what Mail is doing as well.
I'm using Node 16 and NPM 8 for both apps.

No idea what's the difference but there is one for sure.

**Comment by julien-nc** [comment]
I think the issue is not about the way the params string is produced but that we don't use the API properly.
https://docs.gitlab.com/ee/api/todos.html#get-a-list-of-to-do-items
The `action` is supposed to be a string and I guess it's not possible to provide multiple ones.
I'll have a deeper look.

**Comment by julien-nc** [comment]
It works after running `npm update` which updated a lot of `@babel` packages. I thought updating `@nextcloud/logger` would update all necessary dependencies. Apparently not.

Do you think this can be closed or is it necessary to adjust the dependencies of `@nextcloud/logger`?

**Comment by ChristophWurst** [comment]
I don't think there is much this package can influence. So I'm closing this ticket.
