### ISSUE TITLE
Undefined context crashes log()

### ISSUE THREAD

**Issue by sundbry** [nextcloud/nextcloud-logger#7]
Stack trace: 
<img width="533" alt="Screen Shot 2019-08-14 at 9 47 37 AM" src="https://user-images.githubusercontent.com/549273/63039722-c1e6eb80-be78-11e9-8d89-21c5da46d9de.png">

On this line https://github.com/ChristophWurst/nextcloud-logger/blob/master/lib/ConsoleLogger.ts#L13 if a client calls log with a null context, it will throw an exception un context.app and crash the program.

**Comment by susnux** [comment]
Is this not closed with ac1174fbda21be3bf199174a3911135dae11ecd9 ?
